const constants = {
	LOG_IN: "LOG_IN",
	LOG_OUT: "LOG_OUT",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	CANCEL_FETCHING: "CANCEL_FETCHING",
	SET_USER_NAME: "SET_USER_NAME",
	ADD_MESSAGE: "ADD_MESSAGE",
	CLEAR_MESSAGES: "CLEAR_MESSAGES",
	JOIN_CHAT: "JOIN_CHAT",
	ADD_EMOJI: "ADD_EMOJI",
	SHOW_EMOJIS: "SHOW_EMOJIS",
	CONNECT_SOCKET: "CONNECT_SOCKET",
	CHANGE_EMOJI: "CHANGE_EMOJI",
	SET_SCOREBOARD: "SET_SCOREBOARD",
	PLAY_CARD: "PLAY_CARD",
	IS_PLAYING_POKER: "IS_PLAYING_POKER",
	IS_NOT_PLAYING_POKER: "IS_NOT_PLAYING_POKER",
	REMOVE_CARD: "REMOVE_CARD",
	SET_NEW_HAND: "SET_NEW_HAND"
}

export default constants