const constants = {
	LOG_IN: "LOG_IN",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	CANCEL_FETCHING: "CANCEL_FETCHING",
	SET_USER_NAME: "SET_USER_NAME",
	ADD_MESSAGE: "ADD_MESSAGE"
}

export default constants